/*
  Auto-generated by Spline
*/

import useSpline from "@splinetool/r3f-spline";
import { OrthographicCamera } from "@react-three/drei";

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline(
    "https://prod.spline.design/tDNoj3DD2rSJJfyV/scene.splinecode"
  );

  const updateColor = () => {
    // Access the layers of the material
    const layers = materials["Sphere Material"].layers;

    // layers are an array that are listed bottom to top (see spline inspector to see which are on top)
    const colorLayer = layers[0];

    // uniforms keys are auto generated and you need to use the layer id to reconstruct it
    const colorUniform = colorLayer.uniforms[`f${colorLayer.id}_color`];

    // now that you have access to the uniform do what you want with it
    colorUniform.value.setHex(Math.random() * 0xffffff);
  };

  return (
    <>
      
      <group {...props} dispose={null}>
        <mesh
          name="Sphere"
          geometry={nodes.Sphere.geometry}
          material={materials["Sphere Material"]}
          castShadow
          receiveShadow
          position={[-25, 11, 0]}
          onClick={updateColor}
        />
        <directionalLight
          name="Directional Light"
          castShadow
          intensity={0.7}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={1}
          shadow-camera-far={2500}
          shadow-camera-left={-1250}
          shadow-camera-right={1250}
          shadow-camera-top={1250}
          shadow-camera-bottom={-1250}
          position={[200, 300, 300]}
        />
        <OrthographicCamera
          name="Personal Camera"
          makeDefault={true}
          far={100000}
          near={-100000}
          position={[0, 0, 1000]}
        />
        <hemisphereLight
          name="Default Ambient Light"
          intensity={0.75}
          color="#eaeaea"
          position={[0, 1, 0]}
        />
      </group>
    </>
  );
}
